# 项目信息
description = "Tune 是一款专为终端打造的现代化网易云音乐播放器：极简设计、键盘操控、无损音质串流、MPRIS 媒体控制与黑胶播放可视化。欢迎发送 issues 反馈 bug～"
author = "Asniya (@aimy1)"
license = "GNU AGPL-3.0"

# 链接信息
[links]
github_url = "https://github.com/aimy1/tune"
issues_url = "https://github.com/aimy1/tune/issues"

# --- about braille images: begin ---

[[braille_images]]
width = 28
height = 4
art = '''
 ⢀⣀⣀⣀⡀ ⣀⡀ ⣀⡀ ⢀⣀⡀ ⣀⡀ ⢀⣀⣀⡀ 
 ⠈⠙⣿⡏⠁ ⣿⡇ ⣿⡇ ⢸⣿⣷⡀⣿⡇ ⢸⣿⠉⠁ 
   ⣿⡇  ⣿⡇⢀⣿⡇ ⢸⣿⢻⣧⣿⡇ ⢸⣿⠛⠃ 
   ⣿⡇  ⠻⣷⣾⡿⠁ ⢸⣿ ⢻⣿⡇ ⢸⣿⣤⡄ 
'''

[[braille_images]]
width = 38
height = 5
art = '''
 ⢀⣀⣀⣀⣀  ⢀⣀⡀⢀⣀⡀  ⢀⣀⡀ ⢀⣀   ⣀⣀⣀⡀ 
 ⠈⠛⣿⡟⠛  ⢸⣿⡇⢸⣿⡇  ⢸⣿⣿⡄⢸⣿   ⣿⣿⠛⠃ 
   ⣿⡇   ⢸⣿⡇⢸⣿⡇  ⢸⣿⠻⣿⣼⣿   ⣿⣿⠿⠇ 
   ⣿⡇   ⠸⣿⣧⣼⣿⠃  ⢸⣿ ⢻⣿⣿   ⣿⣿⣤⡄ 
   ⠉⠁    ⠈⠉⠉    ⠈⠉  ⠉⠉   ⠉⠉⠉⠁ 
'''

[[braille_images]]
width = 48
height = 6
art = '''
 ⢀⣀⣀⣀⣀⣀  ⣀⣀  ⣀⣀  ⢀⣀⣀  ⣀⣀   ⣀⣀⣀⣀⡀ 
 ⠘⠛⣿⣿⡟⠛  ⣿⣿  ⣿⣿  ⢸⣿⣿⣧ ⣿⣿   ⣿⣿⡟⠛⠃ 
   ⣿⣿⡇   ⣿⣿  ⣿⣿  ⢸⣿⡿⣿⣆⢻⣿   ⣿⣿⣧⣤   
   ⣿⣿⡇   ⣿⣿  ⣿⣿  ⢸⣿⡇⢹⣿⣾⣿   ⣿⣿⡏⠉   
   ⣿⣿⡇   ⠹⣿⣷⣼⣿⠏  ⢸⣿⡇ ⢻⣿⣿   ⣿⣿⣧⣤⡄ 
   ⠉⠉⠁    ⠈⠉⠉⠁   ⠈⠉⠁ ⠈⠉⠉   ⠉⠉⠉⠉⠁ 
'''
# --- about braille images: end ---
