# 项目信息
description = "Tune 是一个基于 Rust 的网易云音乐终端客户端：登录、搜索、歌单浏览、流媒体播放，以及全屏播放可视化。欢迎发送 issues 反馈 bug～"

# 链接信息
[links]
github_url = "https://github.com/fd/tune"

# --- about braille images: begin ---

[[braille_images]]
width = 20
height = 10
art = '''
          ⢀⣴⡆
      ⢀⣴⣿⠟⠁
     ⢠⣿⠟⠁
     ⣿⠏⢀⣀⣀
     ⢿⡄⠻⠿⠿
      ⠙⠶⠤⠄
'''

[[braille_images]]
width = 30
height = 12
art = '''
                ⢀⣀⡀
            ⢀⣠⣾⠟⠁
        ⢀⣠⣴⣿⠟⠁
      ⢠⣾⠟⠁⣿⠁
     ⢠⣿⠏    ⣿
     ⣾⡏     ⣿
     ⣿      ⣿
     ⢿⣇    ⣠⣿
     ⠘⣿⣦⣤⣴⣾⠟⠁
      ⠈⠙⠛⠛⠁
'''

[[braille_images]]
width = 60
height = 32
art = '''
                      ..................
                 ..:::....           ....::...
             ..:::..                       ..:::.
          .::^:.                               .:::.
        .:^^:                                     :^^:
      .^^^:                           ..            :^^:
     :~~^                ..::::.   .^^^^^:           .^^^.
    ^~~:            .:^~~~~~~~~^  .~~^^^^~~^^^^::..    :^~:
   ~~~.         .:^~~~~~~~~~755!. ~~~~~~~~~~~~~~~~~~~^::^~~^
  ~!!.        :~~!~~~~~~~~~~!77!~~~~~~~~~~~~~~~~~~~~~~~~~~^:
 ^!!:       ^!!!!!!!!!!!!!!!~~~~!!!!!!!!!!!!!~~~~!!!~~:..
.!!!      ^!!!!!!!!!!!!!!!!!!.~!!!!!!!!!!!!!!!!!!~:.
.!!!      ^!!!!!!!!!!!!!!!!!!.~!!!!!!!!!!!!!!!!!!~:.
.!!!      ^!!!!!!!!!!!!!!!!!!.~!!!!!!!!!!!!!!!!!!~:.
^77:    :!77!!!777!!!!!!!7??7. :7!!!!!!!!77!!^:.
!77.   ~777777777777777?YYJJJ~  :7777777~^.
777   !?77777777!!?77?5PP55YY:   .777^.
???  !??????7??J: :7PBBBB5PP7     .7?!^:.
7?J:~???????Y55Y.   ?##G~!GGJ       !????7~:.
~JJ?J?JJ?J5GGGP5      ^ .BBGGP^      !J?JJJJJ?!^.
.JJJJJJJPB##GPGY        G###BP^       ~?~?JJJJJJJ?7~:.
 ~YJJYP#&&B! ~#^       5&&&G~        :?J. ^?YJJJJJYYYY?!:.
  7YY5&@#!   :5       !@@B~        ^5GP5!   :?YYJ7~..:!?YYJ7
   75YP7             :@B~        ~G#GJYG5     ::       .JYY~
    !55J.            Y~        ~GG7.   ^P~            ^Y5Y:
     :YP5!                    ~^.        :          .755?.
       !5P5!.                                     .75PY^
         !5PP?:                                 ^JPPY^
           ^JPGP?^.                         .~JPG5?:
             .^?5GG5J!^..             .:^7JPGP57:
                 .^7YPPGPP5YYJJJJJY55PGGP5J!^.
                      ..:~!7??JJJ??7!^:.
'''
# --- about braille images: end ---
